### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arsium** [ranni0225/WRK#1]
Hello Sir,

I did not find an email or whatever you want to contact you. I'm wondering where did you find those .doc files ?

Sincerily yours,
Arsium

**Comment by ranni0225** [comment]
> Hello Sir,
> 
> I did not find an email or whatever you want to contact you. I'm wondering where did you find those .doc files ?
> 
> Sincerily yours, Arsium

https://github.com/HighSchoolSoftwareClub/Windows-Research-Kernel-WRK-/tree/master/NT_Design_Workbook/Get_Workbook

**Comment by arsium** [comment]
> > Hello Sir,
> > I did not find an email or whatever you want to contact you. I'm wondering where did you find those .doc files ?
> > Sincerily yours, Arsium
> 
> https://github.com/HighSchoolSoftwareClub/Windows-Research-Kernel-WRK-/tree/master/NT_Design_Workbook/Get_Workbook

Thx !
